create table if not exists public.beta_chiirl_events (
  id bigint generated by default as identity primary key,
  title text,
  start_datetime text,
  "Online" text,
  tech_category text,
  image_url text,
  "eventUrl" text,
  location text,
  google_maps_url text,
  created_at timestamptz not null default now()
);

create index if not exists beta_chiirl_events_start_datetime_idx
  on public.beta_chiirl_events (start_datetime);
